### ISSUE TITLE
פורמט תאריך הפוך

### ISSUE THREAD

**Issue by elad-sofer** [startach/Jewish#11]
ברשימת התצוגה הפורמט של התאריך הפוך.
![image](https://user-images.githubusercontent.com/44653433/47845732-6f977b00-ddce-11e8-9aac-a87a799f0424.png)

**Comment by dordots** [comment]
יש לשים לב אחידות לאורך כל התצוגות השונות

**Comment by vladir95** [comment]
טופל - ניתן פורמט לא נכון מלכתחילה.
