### ISSUE TITLE
דאבל קליק ליציאה מהאפליקציה

### ISSUE THREAD

**Issue by elad-sofer** [startach/Jewish#13]
כשהאפליקציה על העמוד הראשי ולוחצים על מקש חזור בפלאפון תקפוץ הודעה: האם ברצונך לצאת כן/לא או: לחץ שנית על חזור ליציאה מהאפליקציה, כיום כשלוחצים חזור בעמוד הראשי האפליקציה נסגרת

**Comment by vladir95** [comment]
Done, but should be tested on android to ensure consistent behaviour.

**Comment by elad-sofer** [comment]
בדקתי באנדרואיד ופקד חזור לא מגיב מכל מסך באפליקציה

**Comment by aabg21** [comment]
טופל ונבדק
