### ISSUE TITLE
הוספת אפשרות להצגת בית כנסת על המפה שנבחרה מתוך תצוגת הרשימה

### ISSUE THREAD

**Issue by elad-sofer** [startach/Jewish#14]
כאשר בוחרים בית כנסת מתוך תצוגת הרשימה אזי שתהיה אפשרות להציג את הבית כנסת על המפה

**Comment by dordots** [comment]
לא ברור האיפיון. איפה הכפתור ימוקם ? גיצד זה ייפתח ? האם תהיה אפשרות לחזור לרשימה ?
