### ISSUE TITLE
העלאת מאגרים לשרת

### ISSUE THREAD

**Issue by mosesshalev** [startach/Jewish#26]
- [ ] קבלת כלל האקסלים ממשה

- [ ] הכנסת מידע אקסל משרד הדתות

- [ ] הכנסת מידע אקסל יהודית מצליח

- [ ] הכנסת מידע אקסל מאגר נדרים

- [ ] להוסיף במודל של כל בית כנסת source

יש לציין בשרת בכל מאגר שנכנס את המקור שלו בשדה, למשל מאגר נדרים יסומן עם ערך של
source_name: Nedarim
בכדי שבהמשך נוכל בקליינט להציג את מקור המידע באם יהיה צורך

**Comment by dordots** [comment]
Done by Eran
