### ISSUE TITLE
ייצוג מתאים לשדה

### ISSUE THREAD

**Issue by dordots** [startach/Jewish#41]
(גבוהה) לא מובן מה העמודה "לא ידוע" מתארת – מילאתי את כל הפרמטרים ועדיין מופיע " לא ידוע"  

![image](https://user-images.githubusercontent.com/16417574/58377169-07cf9a00-7f83-11e9-9770-ef2158fb7ec5.png)

**Comment by dordots** [comment]
שדה זה מייצג את זמן העדכון של המניין, זה לא רלוונטי נכון להוספה, יש להסיר את השדה 
                    <ion-col dir="ltr">
                      <span>{{formatTimeRange(event)}}</span>
                    </ion-col>

במסמך 
add-synagogue.html

**Comment by YehudaEi** [comment]
טופל ע"י @mugavri
