### ISSUE TITLE
הוספת אפשרות לניווט - רשימת בתי כנסת

### ISSUE THREAD

**Issue by elad-sofer** [startach/Jewish#7]
יש להוסיף אפשרות לניווט בלחיצה על כפתור נווט או על הכתובת.
![default](https://user-images.githubusercontent.com/44653433/47845104-bedcac00-ddcc-11e8-9983-87ab2dd7ec1a.jpg)

**Comment by dordots** [comment]
איפה כפתור ניווט אמור להיות ? איך הוא ייראה ?

**Comment by vladir95** [comment]
טופל
