### ISSUE TITLE
שינוי התמונה במצב בית כנסת יחיד

### ISSUE THREAD

**Issue by elad-sofer** [startach/Jewish#8]
יש להחליף את התמונה לתמונה שנמצאת במאגר. אם יש תמונה יש להציג. אם לא יש להציג תמונה דיפולטית..

![image](https://user-images.githubusercontent.com/44653433/47845250-301c5f00-ddcd-11e8-80dc-8736a728c455.png)

**Comment by vladir95** [comment]
Duplicate of #31
