### ISSUE TITLE
הוספת CARD להודעת "פקד GPS חסר"

### ISSUE THREAD

**Issue by elad-sofer** [startach/Jewish#9]
יש להוסיף BORDER שחור להודעת השגיאה - בכדי לעשות זאת יש להכניס את ההודעה לCARD.

![image](https://user-images.githubusercontent.com/44653433/47845334-678b0b80-ddcd-11e8-8929-1c65a0d59df1.png)

**Comment by vladir95** [comment]
Duplicate of #30
